### ISSUE TITLE
Filed to download finished record, available on demand

### ISSUE THREAD

**Issue by armanobosyan** [cleeque/boomstream-downloader#5]
Finished record, files are available on demand, without pin.
Getting error message:
----
Traceback (most recent call last):
  File "./boomstream.py", line 271, in <module>
    sys.exit(app.run())
  File "./boomstream.py", line 245, in run
    if len(self.config['mediaData']['records']) == 0:
KeyError: 'records'
----
[boomstream.config.zip](https://github.com/cleeque/boomstream-downloader/files/6353488/boomstream.config.zip)

**Comment by asiunov** [comment]
I think I've fixed this in my fork. You can try it here: https://github.com/asiunov/boomstream-downloader

**Comment by armanobosyan** [comment]
> I think I've fixed this in my fork. You can try it here: https://github.com/asiunov/boomstream-downloader

Thank you Andrey! I tried your fork, got different error.
----
Traceback (most recent call last):
  File "./boomstream.py", line 306, in <module>
    sys.exit(app.run())
  File "./boomstream.py", line 272, in run
    cookies = self.get_access_cookies()
  File "./boomstream.py", line 266, in get_access_cookies
    cookie = json.loads(r.text)["data"]["cookie"]
KeyError: 'data'

----
My setup is:
Ubuntu 20.04.2 LTS
OpenSSL 1.1.1f  31 Mar 2020
curl 7.68.0
python-requests 2.22.0
Python 2.7.18
Python 3.8.5
python-lxml:amd64 4.5.0-1ubuntu0.3 amd64
ffmpeg version 4.2.4-1ubuntu0.1

**Comment by asiunov** [comment]
Oh, seems like the issues page was disabled in my fork. Fixed.

I think something is broken with the authorization step. I've added better handling for this, try now and you will see an error. I expect this to be "Password is invalid" - which is given when the provided pin code does not work.

**Comment by armanobosyan** [comment]
> Oh, seems like the issues page was disabled in my fork. Fixed.
> 
> I think something is broken with the authorization step. I've added better handling for this, try now and you will see an error. I expect this to be "Password is invalid" - which is given when the provided pin code does not work.

Yes, authorization indeed, 
----
Traceback (most recent call last):
  File "./boomstream.py", line 312, in <module>
    sys.exit(app.run())
  File "./boomstream.py", line 278, in run
    cookies = self.get_access_cookies()
  File "./boomstream.py", line 269, in get_access_cookies
    raise ValueError(f"unexpected response on authorization: {r.text}")
ValueError: unexpected response on authorization: {"code":500,"message":"Internal Server Error"}
----

Current content does not require PIN. For example and test please use: el4Eh2sj

**Comment by asiunov** [comment]
Alright, I've pushed a fix. It works now for your video, just remove pin code from the command.

**Comment by armanobosyan** [comment]
@asiunov Confirm latest commit c6b9b02 worked perfect. **Thank you so much!**
